### ISSUE TITLE
kwik3.5 umez

### ISSUE THREAD

**Issue by kwiksher** [kwiksher/issues#1]
```
    ---------------------------------------------------------------------
    【issue1】
    「クイック」パネル左下の歯車アイコンをクリックしても、設定ウィンドウが開かない
    --OSX 10.10.2

    修正確認済
    --OSX10.10.2
    --OSX10.10.3
    --Win7SP1 32bit

    ---------------------------------------------------------------------
    【issue2】
    「クイック」パネルの右下、クラウドアイコン（最新バージョンを確認する）にマウスオーバーしたときの説明が英語
    --OSX10.10.2
    --OSX10.10.3
    --Win7SP1 32bit

     =>
       Updateを更新にしました

    ---------------------------------------------------------------------
    【issue3】
    以前のバージョンのKwik3・Photoshop CS6で作成したプロジェクトが開けない
    （以前のKwik3と互換性がない仕様でしょうか？ 念のため.kwkファイルを送ります）
    添付：uma.kwk
    --OSX10.10.3
    --Win7SP1 32bit

    =>
      uma.kwkがshift.jisでしたのでしたので、 utf-8に保存すると表示できます。

    ---------------------------------------------------------------------
    【issue4】
    コンポーネント一覧、ページ一覧のチェックボックスの位置が少し上に寄っている（最上段はボックス上部が隠れている）
    添付：クイックパネルレイアウト.png
    --OSX10.10.3
    --Win7SP1 32bit

    =>
      cssを少し直して対応してみました。

    ---------------------------------------------------------------------
    【issue5】
    最上階層のメニューの各アイコンをマウスオーバーしたときの説明が英語（Physicsなど）
    --OSX10.10.3
    --Win7SP1 32bit

    =>
      index.htmlの英語を修正
```

---

【issue6】
線形アニメーション > Properties項目内のx: y: の+と-を連続クリック時の反応が遅い
--OSX10.10.3
--Win7SP1 32bitでは問題なし

=>
  未調査

```
    ---------------------------------------------------------------------
    【issue7】
    「レイヤー・グループを隠す」 「変数の作成」を行っても、コンポーネント一覧に表示されない。コンポーネント一覧をクリックするなどリフレッシュされると表示される
    --OSX10.10.3
    --Win7SP1 32bit

     =>
         readProj()を追加

    ---------------------------------------------------------------------
    【issue8】
    「開く」にマウスオーバーすると、「クイック」パネル下部に横スクロールバーが表示される
    添付：クイックパネルレイアウト.png
    --Win7SP1 32bit
    --OSX10.10.3では問題なし

    =>
      cssを直してみた


    ---------------------------------------------------------------------
    【issue9】
    ページ一覧、コンポーネント一覧の縦スクロールバーが不要なのに表示されている。また、左に寄っている。
    添付：クイックパネルレイアウト.png
    --Win7SP1 32bit
    --OSX10.10.3では問題なし

    =>
      cssを直してみた

    ---------------------------------------------------------------------
    【issue10】
    コンポーネント一覧、ページ一覧のアイコンの色（灰色）が薄くて見づらい
    --Win7SP1
    --OSX10.10.3

    =>
      青色にしてみました

    ---------------------------------------------------------------------
    【issue11】
    .logファイルの中身が英語
    （エラーが英語だと、エラー潰しで詰まるノンプログラマーは多いと思うので、日本語だとより親切だと思いました。）
    --Win7SP1

    =>
    日本語にしてみました
```

**Comment by sigtta** [comment]
最新バージョン（150413）での修正確認結果 + 2件追加の報告です。
前回も今回も網羅的なテストは行わず、ランダムに項目を確認しています。
「別添」のファイルは、別途送ります。

---

# 【issue1】 / Close

デグレなし
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue2】 / Open

英語で表示されます。
アイコンの左下部分にマウスホバーしたときのみ、英語に加えて一瞬「更新」が表示されます。
（スクショを撮るのが難しかったので撮っていません。）
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue3】 / Close

uma.kwkをutf-8に保存し直したら、プロジェクトが開けました。
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue4】 / Close

修正確認済
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue5】 / Close

修正確認済み
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue6】 / Open

今回のバージョンも発生します。
別添：Kwik#1-issue6.png
--OSX10.10.3
--Win7SP1 32bitでは問題なし   

マシンの性能依存の可能性があるので、再現マシンのスペックを記載します。
- MacBook Air (13-inch, Mid 2013)
- プロセッサ 1.3 GHz Intel Core i5
- メモリ 4 GB 1600 MHz DDR3
- グラフィックス Intel HD Graphics 5000 1536 MB

---

# 【issue7】 / Close

修正確認済み
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue8】 / Close

修正確認済み
--Win7SP1 32bit

---

# 【issue9】 / Close

修正確認済み
--Win7SP1 32bit

---

# 【issue10】 / Open

アイコンは青色になっておらず、
- （修正前）デフォルト時=暗い灰色、マウスホバー時=橙色
- （修正後）デフォルト時=橙色、マウスホバー時=暗い灰色

になっています。

他のアイコン（「コピー」「ペースト」「削除」など）同様、
- （修正案）デフォルト時=明るい灰色、マウスホバー時=橙色

にするのがよいかと思います。

---

# 【issue11】 / Close

修正確認済み
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue12】（新規） / Open

「クイック」パネルの右下、
クラウドアイコン（更新）にマウスオーバーしたときの画像が表示されない。
別添：Kwik#1-issue12.png
--OSX10.10.3
--Win7SP1 32bit

---

# 【issue13】（新規） / Open

パブリッシュ時にエラーを検知した際に表示される警告ダイアログに脱字
（「プロジェクト」が「プロジェク」になっている）
別添：Kwik#1-issue13.png
--OSX10.10.3
--Win7SP1 32bit
